services:
 web:
  git_url: https://github.com/cloud66-samples/acme.git
  git_branch: master
  dockerfile_path: "./Dockerfile"
  build_root: web
 #store:
 # git_url: https://github.com/cloud66-samples/acme.git
 # git_branch: master
 # dockerfile_path: "./Dockerfile"
 # build_root: store
